[book]
title = "upc_manual"
authors = ["Zhongzhiy"]
language = "en"

[output.html.playground]
editable = true

[output.html]
# 你的 GitHub 仓库完整地址
git-repository-url = "https://github.com/ZhongZhiy/UPC_Manual"
