[book]
title = "upc_manual"
authors = ["Zhongzhiy"]

language = "zh-cn"

[output.html]
# 你的 GitHub 仓库完整地址
git-repository-url = "https://github.com/ZhongZhiy/UPC_Manual"


[output.html.playground]
editable = true



[output.html]
mathjax-support = true

# [preprocessor.admonition]
# command = "mdbook-admonition"
